<?php
/**
 * Created by PhpStorm.
 * User: khem
 * Date: 8/24/16
 * Time: 9:13 AM
 */

namespace KerungRepo\Providers;

use Illuminate\Support\ServiceProvider;

/**
 * Class RepositoryServiceProvider
 * @package KerungRepo\Providers
 * @author Khemrr067@gmail.com <khemrr067@gmail.com>
 */
class RepositoryServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(
            'KerungRepo\Repository\CategoryRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CategoryEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\StockStatusRepositoryInterface',
            'KerungRepo\Repository\Eloquent\StockStatusEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\AttributeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\AttributeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\AttributeGroupRepositoryInterface',
            'KerungRepo\Repository\Eloquent\AttributeGroupEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ManufacturerRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ManufacturerEloquentRepository'
        );
         $this->app->bind(
            'KerungRepo\Repository\ReviewRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ReviewEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\LengthClassRepositoryInterface',
            'KerungRepo\Repository\Eloquent\LengthClassEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\VoucherThemeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\VoucherThemeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\VoucherRepositoryInterface',
            'KerungRepo\Repository\Eloquent\VoucherEloquentRepository'
         );
        $this->app->bind(
            'KerungRepo\Repository\WeightClassRepositoryInterface',
            'KerungRepo\Repository\Eloquent\WeightClassEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductReturnRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductReturnEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductReturnActionRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductReturnActionEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CouponRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CouponEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\SettingRepositoryInterface',
            'KerungRepo\Repository\Eloquent\SettingEloquentRepository'
            );
            $this->app->bind(
            'KerungRepo\Repository\ProductReturnStatusRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductReturnStatusEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductReturnReasonRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductReturnReasonEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CurrencyRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CurrencyEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\StoreRepositoryInterface',
            'KerungRepo\Repository\Eloquent\StoreEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CustomerGroupRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CustomerGroupEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CustomerRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CustomerEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\OrderStatusRepositoryInterface',
            'KerungRepo\Repository\Eloquent\OrderStatusEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductDiscountRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductDiscountEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductAttributeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductAttributeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductImageRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductImageEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\OrderRepositoryInterface',
            'KerungRepo\Repository\Eloquent\OrderEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\BannerRepositoryInterface',
            'KerungRepo\Repository\Eloquent\BannerEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\BannerImageRepositoryInterface',
            'KerungRepo\Repository\Eloquent\BannerImageEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductCategoryRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductCategoryEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\UserRepositoryInterface',
            'KerungRepo\Repository\Eloquent\UserEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\WishListRepositoryInterface',
            'KerungRepo\Repository\Eloquent\WishListEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CountryRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CountryEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\StateRepositoryInterface',
            'KerungRepo\Repository\Eloquent\StateEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CityRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CityEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\AreaRepositoryInterface',
            'KerungRepo\Repository\Eloquent\AreaEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ComboTypeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ComboTypeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ComboOfferRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ComboOfferEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\DiscountRepositoryInterface',
            'KerungRepo\Repository\Eloquent\DiscountEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\DiscountTypeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\DiscountTypeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\DiscountAttributeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\DiscountAttributeEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\ProductRelatedRepositoryInterface',
            'KerungRepo\Repository\Eloquent\ProductRelatedEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\OrderProductRepositoryInterface',
            'KerungRepo\Repository\Eloquent\OrderProductEloquentRepository'
        );
        $this->app->bind(
        'KerungRepo\Repository\CustomerFamilyTypeRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CustomerFamilyTypeEloquentRepository'

        );
        $this->app->bind(
            'KerungRepo\Repository\DurationRepositoryInterface',
            'KerungRepo\Repository\Eloquent\DurationEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\FamilyWishlistRepositoryInterface',
            'KerungRepo\Repository\Eloquent\FamilyWishlistEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\FamilyWishlistProductRepositoryInterface',
            'KerungRepo\Repository\Eloquent\FamilyWishlistProductEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\OrderHistoryRepositoryInterface',
            'KerungRepo\Repository\Eloquent\OrderHistoryEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\CustomerProSugRepositoryInterface',
            'KerungRepo\Repository\Eloquent\CustomerProSugEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\AddressRepositoryInterface',
            'KerungRepo\Repository\Eloquent\AddressEloquentRepository'
        );
        $this->app->bind(
            'KerungRepo\Repository\FeatureProductRepositoryInterface',
            'KerungRepo\Repository\Eloquent\FeatureProductEloquentRepository'
        );

    }
}